from selenium import webdriver
from selenium.webdriver.common.keys import Keys
driver = webdriver.Chrome(r'C:\Python38\chromedriver.exe')
#browser = webdriver.Firefox()
#browser.get('http://inventwithpython.com')
driver.get("http://localhost:5000/application.html")
name=driver.find_element_by_name("name")
email=driver.find_element_by_name("email")
age=driver.find_element_by_name("age")
#gender=driver.find_element_by_name("gender")
#married=driver.find_element_by_name("married")
#dependents=driver.find_element_by_name("dependents")
#education=driver.find_element_by_name("education")
appincome=driver.find_element_by_name("appincome")
coappincome=driver.find_element_by_name("coappincome")
loan_amount=driver.find_element_by_name("loan_amount")
loan_term=driver.find_element_by_name("loan_term")
#credit_history=driver.find_element_by_name("credit_history")
#area=driver.find_element_by_name("area")
#employment=driver.find_element_by_name("employment")

name.send_keys('Siva Kumar')
email.send_keys('aa@gmail.com')
age.send_keys('33')
#gender.send_keys('Male')
#married.send_keys('No')
#dependents.send_keys('0')
#education.send_keys('Graduate')
appincome.send_keys('0')
coappincome.send_keys('0')
loan_amount.get_attribute('0')
loan_term.send_keys('0')
#credit_history.send_keys('No')
#area.send_keys('Urban')
#employment.send_keys('Yes')
#driver.find_element_by_name("submit").click()
#form = driver.find_element_by_id('submit')
#form.submit()
#driver.find_element_by_css_selector("input[name='submit'][value='Submit']").click()
#Gender = driver.find_element_by_id("male")
#Gender.click()
MaritalStatus = driver.find_element_by_id("no")
MaritalStatus.click()
Dependents = driver.find_element_by_id("0")
Dependents.click()
Education = driver.find_element_by_id("education")
Education.click()
Employed = driver.find_element_by_id("e0")
Employed.click()
History = driver.find_element_by_id("c0")
History.click()
Area = driver.find_element_by_id("a2")
Area.click()
#submit=WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "submit"))
 # submit.submit()
